// Code generated by "stringer -type KeyType"; DO NOT EDIT

package gokey

import "fmt"

const _KeyType_name = "EC256EC521RSA2048RSA4096"

var _KeyType_index = [...]uint8{0, 5, 10, 17, 24}

func (i KeyType) String() string {
	if i < 0 || i >= KeyType(len(_KeyType_index)-1) {
		return fmt.Sprintf("KeyType(%d)", i)
	}
	return _KeyType_name[_KeyType_index[i]:_KeyType_index[i+1]]
}
