name: ci

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.17', '>=1.18' ]
    name: Test go${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      
      - name: Run go test
        run: go test ./...
      
      - name: Run go build
        run: go build ./cmd/gokey
