name: ci

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [ 'stable', 'oldstable' ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - go${{ matrix.go }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Test gofmt
        if: runner.os == 'Linux'
        run: test -z "$(gofmt -l .)"
      - name: Run go test
        run: go test ./...
      - name: Run go build
        run: go build ./cmd/gokey
