name: Publish release binaries

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest , windows-latest ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - go${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'
          check-latest: true
      - name: Run go build
        run: go build ./cmd/gokey
      - name: Upload Linux binary
        if: runner.os == 'Linux'
        run: |
          mv gokey gokey-${{ github.ref_name }}-linux-amd64
          gh release upload ${{ github.ref_name }} gokey-${{ github.ref_name }}-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Windows binary
        if: runner.os == 'Windows'
        run: |
          mv gokey.exe gokey-${{ github.ref_name }}-windows-amd64.exe
          gh release upload ${{ github.ref_name }} gokey-${{ github.ref_name }}-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload MacOS binary
        if: runner.os == 'macOS'
        run: |
          mv gokey gokey-${{ github.ref_name }}-darwin-amd64
          gh release upload ${{ github.ref_name }} gokey-${{ github.ref_name }}-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
